# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: joatmon08/tech-portfolio
    steps:
    - uses: actions/checkout@v3
    - name: Install GLIBC (libc6) dependency
      run: |
          apt-get update && apt-get install -y libc6
    - name: Install dependencies and static website
      run: |
        cd website
        yarn install
        yarn build
    - name: Push to Github Pages branch
      run: |
        cd website/build/tech-portfolio
        touch .nojekyll
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} INPUT_DIRECTORY=$(pwd) publish.sh
        
